### ISSUE TITLE
Bug. "Help center" - interface translation

### ISSUE THREAD

**Issue by daniil5469** [tourhunter-com/help-tourhunter-com#126]
Translate interface on second language (Russian) for the next sections:

- [x] Searchbar in the second header;

- [x] Footer;

- [x] "More categories";

- [x] "Articles in this categories";

- [x] "Categories";

- [x] "Related articles".

**Attachments:**

![searchbar_translate](https://user-images.githubusercontent.com/40592637/77875645-60ce2580-7259-11ea-811e-80491bce3927.png)

![footer_translate](https://user-images.githubusercontent.com/40592637/77875743-a4c12a80-7259-11ea-9811-d98389991895.png)

![more-categories_translate](https://user-images.githubusercontent.com/40592637/77876301-37ae9480-725b-11ea-9130-6021a1308cfe.png)

![aricles-in-this-category_translate](https://user-images.githubusercontent.com/40592637/77876389-780e1280-725b-11ea-8a22-446d89f311e9.png)

![categories_translate](https://user-images.githubusercontent.com/40592637/77876437-a25fd000-725b-11ea-80c4-82ad7bf6f98e.png)

![related-articles_translate](https://user-images.githubusercontent.com/40592637/77876524-e0f58a80-725b-11ea-99c3-1e600e643ab1.png)

Сделать перевод интерфейса, там где это технически еще не реализовано (блоки и скриншоты  указаны выше).

**Comment by fsuaterdogan** [comment]
Hi. Is this true? Categories | категории, Related articles | Статьи по Теме, Articles in this category | Статьи в этой категории, More categories | Больше категорий, What can we help you with? | Чем мы можем вам помочь?

**Comment by daniil5469** [comment]
Fix has been tested successfully.
