### ISSUE TITLE
Bug [stage]. "Help Center" search doesn't work

### ISSUE THREAD

**Issue by daniil5469** [tourhunter-com/help-tourhunter-com#132]
**Environment:**

 Windows 10 Pro - Version 1903 (Build - 18362.720), Chrome - Version 80.0.3987.163 (Official Build) (64-bit)

**Steps to reproduce:**

1 - Go to main page of "Help Center".

2 - Type any word in searchbar.

**Actual Result:**

Search doesn't work.

**Expected Result:**

The search should work on the title and content of the articles in the language that is currently selected for the site.

**Attachments:**

![bug_searching](https://user-images.githubusercontent.com/40592637/78664020-d67e6500-78db-11ea-9725-46f726d756d0.png)

**Шаги воспроизведения:**

1 - Перейти на главную страницу "Help Center".

2 - Ввести любое слово в строке поиска.

**Фактический результат:**

Поиск не работает.

**Ожидаемый результат:**

Поиск должен работать по названию и содержимому статей, на том языке, который выбран сейчас для сайта.

**Приложения:** см. выше.

**Comment by fsuaterdogan** [comment]
The Russian alphabet cannot be printed on JSONs. We should consider something else or try another solution from Simple-Jekyll-Search.

**Comment by daniil5469** [comment]
1. There are errors in console tab 

2. The search should work on the title and content of the articles in the language that is currently selected for the site. Now it shows results on two languages and not which was seleted in the header.

![bug-searchbar](https://user-images.githubusercontent.com/40592637/79105142-bab20d80-7d78-11ea-861e-3df55c8ae242.png)

**Comment by fsuaterdogan** [comment]
As I said in [here](https://github.com/tourhunter-com/help-tourhunter-com/pull/137), the console is giving because of a bug. It is working fine.

**Comment by daniil5469** [comment]
A last one error is displayed in the console.

![console_bug](https://user-images.githubusercontent.com/40592637/79192625-bd246e00-7e31-11ea-8a76-8bc1c55fa147.png)

**Comment by daniil5469** [comment]
Fix has been tested successfully.
