### ISSUE TITLE
Bug. "Help Center" - article doesn't display when you change the language and redirects to main page

### ISSUE THREAD

**Issue by daniil5469** [tourhunter-com/help-tourhunter-com#15]
**Environment:** Windows 10, Google Chrome Version 78.0.3904.97 (Official Build) (64-bit)

**Steps to reproduce:**

1 - Go to main page of "Help Center".

2 - Find the category "Getting Started" and open her.

3 - Open existing article. For example "Aget Company".

4 - Change the language.

**Actual Result:** when language is changing user redirects to the main page.

**Expected Result:** when language is changing user stays on opened page if there is a selected translation.

**Attachments:**

![ice_video_20191111-094842_edit_0](https://user-images.githubusercontent.com/40592637/68570149-9fa93d80-0468-11ea-92b0-f1a81403c0d8.gif)

***

**Шаги воспроизведения:**

1 - Перейти на главную страницу "Help Center".

2 - Найти категорию "Getting Started" и открыть её.

3 - Открыть существующую статью. Например, "Aget Company".

4 - Изменить язык.

**Фактический результат:** когда меняется язык, пользователя перенаправляет на главную страницу.

**Ожидаемый результат:** когда меняется язык, пользователь должен остаться на открытой странице, если есть выбранный перевод.

**Приложения:** см. выше.

**Comment by logicdigger** [comment]
i have looked at . pages not seems created would be fix all 

https://help.tourhunter.com/ru/category/what-s-new-in-tourhunter


you may contact me on https://www.fiverr.com/logicdiggerlabs

**Comment by Alboroz** [comment]
For this problem:  in rus language there is the  getting started.md file?

**Comment by logicdigger** [comment]
I need to look in can you provide logins

**Comment by daniil5469** [comment]
The problem with unexisting the getting started.md file has been successfully resolved.

The second part with redirects when we change the language staying unresolved.

**Comment by Website-tech** [comment]
I have been working hard and smart to solve all the 3 issues

**Comment by daniil5469** [comment]
Fix has been tested successfully.
